INSERT INTO `musicas` (`Titulo`, `Artista`, `Estilo`, `AnoLançamento`) VALUES
('Águas de Março', 'Tom Jobim e Elis Regina', 'MPB', '1972'),
('Alegria, Alegria', 'Caetano Veloso', 'Tropicália', '1967'),
('Garota de Ipanema', 'Tom Jobim e Vinicius de Moraes', 'Bossa Nova', '1962'),
('Mas que Nada', 'Jorge Ben Jor', 'Samba Rock', '1963'),
('País Tropical', 'Jorge Ben Jor', 'Samba Rock', '1969'),
('Carinhoso', 'Pixinguinha e João de Barro', 'Choro', '1917'),
('Asa Branca', 'Luiz Gonzaga e Humberto Teixeira', 'Forró', '1947'),
('Trem Bala', 'Ana Vilela', 'Pop Folk', '2016'),
('Ai Se Eu Te Pego', 'Michel Teló', 'Sertanejo Universitário', '2011'),
('Show das Poderosas', 'Anitta', 'Funk Carioca', '2013'),
('Montero (Call Me By Your Name)', 'Lil Nas X', 'Rap/Pop/Rock', '2021'),
('Jalebi Baby', 'Tesher', 'Hip Hop/Bhangra', '2021'),
('Butter', 'BTS', 'K-pop', '2021'),
('Modo Turbo', 'Luísa Sonza, Anitta e Pabllo Vittar', 'Funk Pop', '2020'),
('Batom de Cereja', 'Israel e Rodolffo', 'Sertanejo Universitário', '2021'),
('Facas', 'Diego & Victor Hugo feat. Bruno & Marrone', 'Sertanejo Romântico', '2020'),
('Águas de Março', 'Tom Jobim e Elis Regina', 'MPB', '1972'),
('Alegria, Alegria', 'Caetano Veloso', 'Tropicália', '1967'),
('As Rosas Não Falam', 'Cartola', 'Samba', '1976'),
('Evidências', 'Chitãozinho & Xororó', 'Sertanejo Clássico', '1990'),
('Eu Sei que Vou Te Amar', 'Vinícius de Moraes', 'Bossa Nova', '1959'),
('Quero Que Vá Tudo para o Inferno', 'Roberto Carlos', 'Jovem Guarda', '1965'),
('Tropicália', 'Caetano Veloso', 'Tropicália', '1968'),
('Ouro de Tolo', 'Raul Seixas', 'Rock', '1973'),
('Panis et Circencis', 'Os Mutantes', 'Rock Psicodélico', '1968'),
('O Mundo é um Moinho', 'Cartola', 'Samba', '1976'),
('Desafinado', 'João Gilberto', 'Bossa Nova', '1958'),
('Trem das Onze', 'Demônios da Garoa', 'Samba Paulista', '1964'),
('Aquarela do Brasil', 'Francisco Alves', 'Samba-Exaltação', '1939'),
('Evidências', 'Chitãozinho & Xororó', 'Sertanejo Clássico', '1990'),
('Garota de Ipanema', 'Tom Jobim e Vinicius de Moraes', 'Bossa Nova', '1962'),
('Mas que Nada', 'Jorge Ben Jor', 'Samba Rock', '1963'),
('País Tropical', 'Jorge Ben Jor', 'Samba Rock', '1969'),
('Carinhoso', 'Pixinguinha e João de Barro', 'Choro', '1917'),
('Chega de Saudade', 'João Gilberto', 'Bossa Nova', '1958'),
('Como Nossos Pais', 'Elis Regina', 'MPB', '1976'),
('Canto de Ossanha', 'Baden Powell e Vinicius de Moraes','Afro-Samba','1966'),
('Batom de Cereja','Israel e Rodolffo','Sertanejo Universitário','2021'),
('Montero (Call Me By Your Name)','Lil Nas X','Rap/Pop/Rock','2021'),
('Jalebi Baby','Tesher','Hip Hop/Bhangra','2021'),
('Butter','BTS','K-pop','2021'),
('Modo Turbo','Luísa Sonza, Anitta e Pabllo Vittar','Funk Pop','2020'),
('Facas','Diego & Victor Hugo feat. Bruno & Marrone','Sertanejo Romântico','2020'),
('As Rosas Não Falam','Cartola','Samba','1976'),
('Águas de Março','Tom Jobim e Elis Regina','MPB','1972'),
('Alegria, Alegria','Caetano Veloso','Tropicália','1967'),
('Show das Poderosas','Anitta','Funk Carioca','2013'),
('Trem Bala','Ana Vilela','Pop Folk','2016'),
('Asa Branca','Luiz Gonzaga e Humberto Teixeira','Forró','1947'),
('Faroeste Caboclo', 'Legião Urbana', 'Rock', '1987'),
('Eduardo e Mônica', 'Legião Urbana', 'Rock', '1986'),
('Pais e Filhos', 'Legião Urbana', 'Rock', '1989'),
('Epitáfio', 'Titãs', 'Rock', '2001'),
('Meu Erro', 'Paralamas do Sucesso', 'Rock', '1984'),
('Lanterna dos Afogados', 'Paralamas do Sucesso', 'Rock', '1989'),
('Anna Júlia', 'Los Hermanos', 'Rock Alternativo', '1999'),
('Velha Infância', 'Tribalistas', 'MPB/Pop Rock', '2002'),
('Malandragem', 'Cássia Eller', 'MPB/Rock/Blues', '1994'),
('Por Enquanto', 'Cássia Eller', 'MPB/Rock/Blues', '1990'),
('Sozinho', 'Caetano Veloso', 'MPB/Pop Rock', '1998'),
('Você Não Me Ensinou a Te Esquecer', 'Caetano Veloso','MPB/Pop Rock','2000'),
('O Leãozinho','Caetano Veloso','MPB/Pop Rock','1977'),
('Andança','Beth Carvalho','Samba','1968'),
('Coisinha do Pai','Beth Carvalho','Samba','1979'),
('Vou Festejar','Beth Carvalho','Samba','1978'),
('Fogo e Paixão','Wando','Brega','1988'),
('Amor I Love You','Marisa Monte','MPB/Pop Rock','2000'),
('Ainda Bem','Marisa Monte','MPB/Pop Rock','2011'),
('Não Vá Embora','Marisa Monte','MPB/Pop Rock','1994'),
('Rock Around the Clock', 'Nora Ney', 'Rock and Roll', '1955'),
('Rock and Roll em Copacabana', 'Cauby Peixoto', 'Rock and Roll', '1957'),
('Banho de Lua', 'Celly Campello', 'Rock and Roll', '1960'),
('Splish Splash', 'Roberto Carlos', 'Jovem Guarda', '1963'),
('Festa de Arromba', 'Erasmo Carlos', 'Jovem Guarda', '1965'),
('Pro Dia Nascer Feliz', 'Barão Vermelho', 'Rock', '1983'),
('Será', 'Legião Urbana', 'Rock', '1985'),
('Aluga-se', 'Raul Seixas', 'Rock', '1980'),
('Meu Erro', 'Paralamas do Sucesso', 'Rock', '1984'),
('Bete Balanço', 'Barão Vermelho', 'Rock', '1984'),
('Die for you', 'The Weeknd', 'Pop', '2015'),
  ('Plaptudum', 'Dj Anininha', 'Funk', '2015'),
  ('Shape of You', 'Ed Sheeran', 'Pop', '2017'),
  ('Blinding Lights', 'The Weeknd', 'Pop', '2020'),
  ('Uptown Funk', 'Mark Ronson ft. Bruno Mars', 'Funk', '2014'),
  ('Bohemian Rhapsody', 'Queen', 'Rock', '1975'),
  ('Billie Jean', 'Michael Jackson', 'Pop', '1982'),
  ('Bohemian Rhapsody', 'Queen', 'Rock', '1975'),
  ('Shape of You', 'Ed Sheeran', 'Pop', '2017'),
  ('Blinding Lights', 'The Weeknd', 'Pop', '2020'),
  ('Imagine', 'John Lennon', 'Pop', '1971'),
  ('Rolling in the Deep', 'Adele', 'Pop', '2010'),
  ('Someone Like You', 'Adele', 'Pop', '2011'),
  ('Hotel California', 'Eagles', 'Rock', '1976'),
  ('Rolling in the Deep', 'Adele', 'Pop', '2010'),
  ('Smells Like Teen Spirit', 'Nirvana', 'Grunge', '1991'),
  ('Imagine', 'John Lennon', 'Pop Rock', '1971'),
  ('Stairway to Heaven', 'Led Zeppelin', 'Hard Rock', '1971'),
  ('Thriller', 'Michael Jackson', 'Pop', '1982'),
  ('I Will Always Love You', 'Whitney Houston', 'Pop Soul', '1992'),
  ('Losing My Religion', 'R.E.M.', 'Alternative Rock', '1991'),
  ('Like a Rolling Stone', 'Bob Dylan', 'Folk Rock', '1965'),
  ('Hey Jude', 'The Beatles', 'Pop Rock', '1968'),
  ('Livin on a Prayer', 'Bon Jovi', 'Hard Rock', '1986'),
  ('Dont Stop Believin', 'Journey', 'Rock', '1981'),
  ('Halo', 'Beyoncé', 'Pop R&B', '2008'),
  ('Shape of You', 'Ed Sheeran', 'Pop Dancehall', '2017'),
  ('Wonderwall', 'Oasis', 'Britpop', '1995'),
  ('Sweet Child O Mine', 'Guns N Roses', 'Hard Rock', '1987'),
  ('Eye of the Tiger', 'Survivor', 'Rock', '1982'),
  ('I Want It That Way', 'Backstreet Boys', 'Pop Boy Band', '1999'),
  ('My Heart Will Go On', 'Celine Dion', 'Pop Ballad', '1997'),
  ('Let It Go', 'Idina Menzel (Frozen)', 'Pop Musical Theatre ', '2013'),
  ('Despacito (Remix)', 'Luis Fonsi, Daddy Yankee, Justin Bieber', 'Pop Reggaeton', '2017'),
  ('Bad Guy','Billie Eilish','Pop Electropop','2019'),
  ('Shallow','Lady Gaga, Bradley Cooper','Pop Country','2018'),
  ('Happy','Pharrell Williams','Pop Funk','2013'),
  ('Wannabe','Spice Girls','Pop Dance-pop','1996'),
  ('I Gotta Feeling','The Black Eyed Peas','Pop Dance-pop','2009'),
  ('Uptown Funk','Mark Ronson, Bruno Mars','Pop Funk','2014'),
  ('Lose Yourself','Eminem','Rap Hip Hop','2002'),
  ('Hips Dont Lie','Shakira, Wyclef Jean','Pop Latin Pop','2006'),
  ('Cant Hold Us','Macklemore & Ryan Lewis, Ray Dalton','Rap Hip Hop','2011'),
  ('Dancing Queen','ABBA','Pop Disco','1976'),
  ('I Will Survive','Gloria Gaynor','Pop Disco','1978'),
('Sólido', 'Terno Rei', 'Indie Rock', '2019'),
('Violeta', 'Terno Rei', 'Indie Rock', '2019'),
('Medo', 'Terno Rei', 'Indie Rock', '2019'),
('Culpa', 'O Terno', 'Indie Rock', '2014'),
('Ai, Ai, Como Eu Me Iludo', 'O Terno', 'Indie Rock', '2014'),
('Volta', 'O Terno', 'Indie Rock', '2016'),
('Amor Marginal', 'Johnny Hooker', 'Indie Pop', '2015'),
('Flutua', 'Johnny Hooker feat. Liniker', 'Indie Pop', '2017'),
('Benzin', 'Boogarins', 'Indie Psicodélico', '2019'),
('6000 Dias (Ou Mantra dos 20 Anos)', 'Boogarins','Indie Psicodélico','2015');
