INSERT INTO `usuarios` (`Nome`, `Username`, `Password`)
VALUES
  ('Davi', 'davifatal', '123'),
  ('Pedro', 'kropz', '456'),
  ('Pamela', 'mochilinha', '789'),
  ('Samuel', 'naotenhodona', '987'),
  ('Rafael', 'nepo', '654');

-- Inserir dados na tabela "reviews"
INSERT INTO `reviews` (`MusicaID`, `Username`, `Comentario`)
VALUES
  (1, 'davifatal', 'Não consigo dormir antes de escutar esssa'),
  (1, 'naotenhodona', 'Me faz lembrar da minha ex'),
  (2, 'kropz', 'Minha namorada adora essa'),
  (2, 'mochilinha', 'Meu namorado odeia essa'),
  (2, 'nepo', 'Essa sempre causa briga de casal'),
  (12, 'davifatal', 'Só escuto essa em loop'),
  (12, 'kropz', 'O davi ama essa musica'),
  (35, 'nepo', 'Achei a letra muito profunda.'),
  (35, 'naotenhodona', 'Essa foi hit em Santa Margarida'),
  (35, 'davifatal', 'Pessoal da roça adora essa'),
  (89, 'mochilinha', 'Quem dera o terno rei fazer uma dessas'),
  (89, 'davifatal', 'Quem gosta dessa tem que ter uma vida muito ruim'),
  (21, 'kropz', 'Me lembra da minha infancia nas ruas de terra de Tchotcho'),
  (21, 'mochilinha', 'Coloco essa quando meu namorado fica com saudades de casa'),
  (21, 'naotenhodona', 'Tem toques de Mozard e Shopan'),
  (5, 'davifatal', 'Essa veio de Corinto, chique com Borra'),
  (5, 'kropz', 'O musica top, pessoal de Corinto sabe das coisas'),
  (5, 'mochilinha', 'Depois dessa meu sonho é ir pra Corinto'),
  (5, 'naotenhodona', 'Poderia ser facilmente o hino do Brasil'),
  (5, 'nepo', 'Quem falar que não gosta dessa é louco, Corinto manda muito'),
  (43, 'naotenhodona', 'Salvar pra escutar depois do culto'),
  (7, 'nepo', 'Sempre coloco nos meus dates'),
  (7, 'mochilinha', 'Red flag total essa musica'),
  (15, 'davifatal', 'Meus amigos só escutam essa'),
  (15, 'kropz', 'O Davi sabe muito, conquistei minha namorada com essa'),
  (15, 'mochilinha', 'Meu namorado acertou muito em apresentando essa'),
  (75, 'nepo', 'Chora muito quando escuto essa'),
  (75, 'naotenhodona', 'Fico muito feliz escutando essa'),
  (75, 'davifatal', 'Essa musica pode causar revoluçoes'),
  (75, 'kropz', 'Essa musica é a mais romantica que conheço'),
  (75, 'mochilinha', 'Essa me da muito sono'),
  (9, 'davifatal', 'Theodoro e Sampaio se inspiraram nessa'),
  (9, 'naotenhodona', 'Luisa Sonza se inspirou nessa'),
  (9, 'kropz', 'Amado Batista se inspirou nessa'),
  (9, 'mochilinha', 'Lana Del Rey se inspirou nessa'),
  (9, 'nepo', 'A Xuxa se inspirou nessa no ilailarie'),
  (54, 'nepo', 'Hit do Carnaval 2022'),
  (90, 'davifatal', 'Hit do Carnaval 2021'),
  (112, 'mochilinha', 'Hit do Carnaval 2020'),
  (16, 'kropz', 'Hit do Carnaval 2019'),
  (58, 'naotenhodona', 'Hit do Carnaval 2025');

-- Inserir dados na tabela "playlists"
INSERT INTO `playlists` (`Nome`, `Descricao`, `Username`)
VALUES
  ('Os melhores louvores antigos', 'Os melhores louvores dos anos 2000', 'naotenhodona'),
  ('Festa Animada em Corinto', 'Só as tops, paredões da cidade pra dançar um forrozin', 'davifatal'),
  ('Para ouvir e dormir', 'Não consigo dar minha opnião porque sempre durmo', 'mochilinha'),
  ('Terno Rei e Terno Rei', 'Nada além de terno rei', 'kropz'),
  ('Pagodin e Pinguinha', 'Pra escutar num churrasquin', 'nepo'),
  ('Festa triste em Corinto', 'Aquelas que toca a partir das 2 da manhã', 'davifatal'),
  ('O Terno e o Terno', 'Nada além de o Terno', 'kropz'),
  ('Funk Pesadão', 'Oq escuto quando ninguém está por perto', 'naotenhodona'),
  ('Para ouvir quando estou acordada', 'Essas eu posso falar que são boas', 'mochilinha'),
  ('Forrozin e Pinguinha', 'Pra escutar no forrozin', 'nepo'),
  ('Festa normal em Corinto', 'Aquelas que tocam em matiné', 'davifatal'),
  ('Louvores de Redenção', 'Para se arrepnder', 'naotenhodona'),
  ('Frank Ocean e Frank Ocean', 'Nada além de Frank Ocean', 'kropz'),
  ('Samba e Pinguinha', 'Acho que estou bebendo muito', 'nepo'),
  ('Para escutar quando estou cansada', 'Essas eu consigo avaliar até a metade', 'mochilinha');

-- Inserir dados na tabela "musicas_playlists"
INSERT INTO `musicas_playlists` (`PlaylistID`, `MusicaID`)
VALUES

  (1, 12),
  (2, 23),
  (3, 14),
  (4, 67),
  (5, 34),
  (6, 31),
  (7, 9),
  (8, 2),
  (9, 56),
  (10, 17),
  (11, 100),
  (12, 87),
  (13, 43),
  (14, 25),
  (15, 112),
  (1, 67),
  (2, 32),
  (3, 143),
  (4, 118),
  (5, 79),
  (6, 51),
  (7, 90),
  (8, 143),
  (9, 7),
  (10, 68),
  (11, 5),
  (12, 75),
  (13, 89),
  (14, 21),
  (15, 112);